### ISSUE TITLE
libsmb2 static library fails to connect server - Windows

### ISSUE THREAD

**Issue by Rajakumar1988** [sahlberg/libsmb2#119]
Static library build with disabling GSSAPI and openSSL for windows fails to connect to server.

ERROR Received:
     smb2_connect_share_async failed ,Invalid address: Can not resolve into IPv4/v6.

SMB urls used to connect server - failed
      smb://username@server/share?sec=ntlmssp
      smb://username@server/share
      smb://domain;username@server/share.

**Comment by timmeh87** [comment]
Hello, I have found the soulution to this problem because I just had it today

On windows, you have to initialize winsock manually to use libsmb2. This is done by calling wsastartup
https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-wsastartup

I would like to suggest to the curators of this library that the windows specific error code for "winsock was not initialized" is caught individually and a more specific error message is displayed.
(another soultion is that Libsmb2 could internally initialize winsock on windows platforms when init_context() is called)

The updated code would be (i did not test this):
socket.c, around line 717:

   ```
     /* is it a hostname ? */
        err = getaddrinfo(host, port, NULL, &ai);
        if (err != 0) {
                free(addr);
				if (err == 10093)
				{
					smb2_set_error(smb2, "Invalid address:%s  "
						"Can not resolv into IPv4/v6.", server);
				}
				else
				{
					smb2_set_error(smb2, "Winsock was not initialized! Call wsastartup()", server);
				}
                switch (err) {
					case 10093:
						return 10093;
...
```


by using 10093 literally the code is automatically portable (dont think linux will ever generate an error code like this) but it might be better to use some kind of "#ifdef WINDOWS" and the proper definition in windows, which is WSANOTINITIALISED

Also there is a typo in the original error string, "resolve" is missing the "e"

**Comment by sahlberg** [comment]
Nice. 

Can you clean up the patch and send it as a pull request so you get proper credits?

I don't think we should initialize winsock from the library since it may have side effects but we should make it more visible the application must do it before calling into libsmb2.
To do this, can you update all the example utils in ./examples to have an #ifdef block for windows to initialize winsock?

**Comment by sahlberg** [comment]
We have code for this now.
