### ISSUE TITLE
Building on Linux Mint

### ISSUE THREAD

**Issue by MilanFranc** [sahlberg/libsmb2#125]
Hi,
I had small issue with building your library on Linux. I figgured out that I miss two packages: OpenSSL  (name: libssl-dev)  and GSSAPI (name: libkrb5-dev).
It would be nice to have it in your readme that these packages are needed for build.

Thank you.

**Comment by sahlberg** [comment]
Were you building from an old version of libsmb2?

The openssl dependency was removed in june 2018 since it turned out it was not licence compatible with e16f6d4036661e45b0076b57946fb7db93b0c0de

The hard dependency on librkb5-dev has also been removed as we not have a built-in
ntlmssp implementation.
