### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by tguillem** [sahlberg/libsmb2#162]
This commit 132fdf5e8bb408bcac8ba34a3d99ca2f6fd143c6 "dcerpc: add example of NetShareGetInf" moved some declarations to a header that is not available on v3.0.0.

This makes impossible to libsmb2 users to handle any versions coming after v3.0.0.
Either you include a non-existing file: "libsmb2-dcerpc-srvsvc.h" or you get undefined types.

Support for MAJOR/MINOR versions in headers could be helpful too.

**Comment by sahlberg** [comment]
On Fri, Oct 9, 2020 at 10:26 PM Thomas Guillem <notifications@github.com>
wrote:

> This commit 132fdf5
> <https://github.com/sahlberg/libsmb2/commit/132fdf5e8bb408bcac8ba34a3d99ca2f6fd143c6>
> "dcerpc: add example of NetShareGetInf" moved some declarations to a header
> that is not available on v3.0.0.
>
> This makes impossible to libsmb2 users to handle any versions coming after
> v3.0.0.
> Either you include a non-existing file: "libsmb2-dcerpc-srvsvc.h" or you
> get undefined types.
>
My bad.
It is unfortunate and a screwup from my side.
The underlying reason is that initially I mixed smb2 as well as the dcerpc
(which originally was only meant for share enum)
which was a mistake. Going forward I want to separate out dcerpc as much as
possible so that eventually it can become a separate
library, or at least make it possible to detach from the dependency of
smb2, which is just one of many transports.

I have done a patch in master to include the new header from libsmb2.h to
restore visibility to these symbols to apps that depend on share enum. Not
ideal solution but it should work.

Please let me know if you have better ideas on how to fix this.


Support for MAJOR/MINOR versions in headers could be helpful too.

**Comment by tguillem** [comment]
Thanks a lot! It will simplify a lot for us.

So, no need to rush for a release then. This solution is simpler.
