### ISSUE TITLE
Parallel connections to shares of the same server fail.

### ISSUE THREAD

**Issue by s-devyatkin** [sahlberg/libsmb2#183]
Attempts to concurrently connect to share (or different shares) of the same server by smb2_connect_share or smb2_connect_share_async (with different smb2_context, of course) fail with error "Wrong signature in received PDU". The error is generated in libsmb2.c. Using mutex on smb2_connect_share solves this problem, but not for for async version. Maybe I'm wrong, but it looks like a bug. Detected on Debian 9.

One more question. Is there a way to use a single connection to the server for all its shares?

**Comment by delins** [comment]
Do you still have this problem? I have a similar use case, running on Ubuntu 18.04, but I haven't had any issues connecting to multiple shares asynchronously (both on the same machine and different ones). 

Could you attach an mwe that reproduces the problem? It could also be useful to explicitly set all of `smb2_set_security_mode`, `smb2_set_seal`, `smb2_set_sign` and `smb2_set_authentication` in the mwe so that it's clearer what connection parameters may cause it.

**Comment by s-devyatkin** [comment]
```
#include <stdint.h>
#include <string.h>
#include <iostream>
#include <future>
#include "smb2.h"
#include "libsmb2.h"

void task(const char* server, const char* share, const char* path, const char* user, const char* password)
{
    struct smb2_context *smb2;
    struct smb2_stat_64 st;

    smb2 = smb2_init_context();
    if (smb2 == NULL)
    {
        std::cerr << "Failed to init context" << std::endl;
        return;
    }

    smb2_set_user(smb2, user);
    smb2_set_password(smb2, password);
    smb2_set_sign(smb2, 1);
    smb2_set_seal(smb2, 1);
    smb2_set_security_mode(smb2, SMB2_NEGOTIATE_SIGNING_ENABLED);

    if (smb2_connect_share(smb2, server, share, 0) != 0)
    {
        std::cerr << "smb2_connect_share failed: " << smb2_get_error(smb2) << std::endl;
        return;
    }

    if (smb2_stat(smb2, path, &st) < 0)
    {
        std::cerr << "smb2_stat failed: " << smb2_get_error(smb2) << std::endl;
        return;
    }

    std::cerr << "success" << std::endl;

    smb2_disconnect_share(smb2);
    smb2_destroy_context(smb2);
}

int main(int argc, char *argv[])
{
    auto t1 = std::async(std::launch::async, &task, "server", "share", "file", "user", "password");
    auto t2 = std::async(std::launch::async, &task, "server", "share", "file", "user", "password");
    t1.wait();
    t2.wait();

    return 0;
}
```

Problem isn't stable. I run above code many times on local share and my output most often looks like that:
```
smb2_connect_share failed: Wrong signature in received PDU
smb2_connect_share failed: smb2_service failed with : 
```


Setting one flag at a time gives different behavior.
When only `smb2_set_security_mode` flag is enabled, the problem appears quite rarely.
With `smb2_set_seal` flag, the problem is rather stable.
When `smb2_set_sign` flag is set, the problem is generated even for a single task.

**Comment by delins** [comment]
I can reproduce the problems on my system playing with `smb2_set_seal` and `smb2_set_sign`; I kept `smb2_set_security_mode(smb2, SMB2_NEGOTIATE_SIGNING_ENABLED);` unchanged.

**Wrong signature**
When `smb2_set_sign` is set I get `Wrong signature in received PDU`, regardless of how many threads the program uses. This may be the same problem as described in #185 and #176. I've modified smb2-signing.c so that it prints the calculated signatures and created a pcap of the SMB2 traffic to see what signatures the server sends us. All signatures are calculated correctly until we get to the `Create Response File` packet, which contains 3 SMB2 pdu's: the signature for the first SMB pdu matches and the those for the other two fail.

The last two pdu's have the `Chained` flag set and the first one does not. I checked whether the [standard](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-SMB2/[MS-SMB2].pdf) has anything to say about how signatures need to be calculated in case of chained pdu's and found a note on it in section "3.1.5.1 Verifying an Incoming Message". I then checked if libsmb2's signature code does anything special in case of pdu's that have the `Chained` flag set, but I didn't find anything. @sahlberg Could this be the source of the issue?

**Failed to decrypt**
When `smb2_set_seal` is set and multiple threads are used as shown in the mwe it sometimes fails (and sometimes a single thread, sometimes both) with `Failed to decrypt PDU`. Sounds like a race condition so I started looking for global variables in aes related code and found some in aes.c under the section `Private variables`. That is likely the cause of the problem. I think the cleanest fix would be to make these members of the `smb2` object, but the aes code is `smb2_context` unaware. Perhaps making them thread local would be a good solution, I don't know.

**Comment by sahlberg** [comment]
On Tue, Jan 26, 2021 at 7:03 AM delins <notifications@github.com> wrote:

> I can reproduce the problems on my system playing with smb2_set_seal and
> smb2_set_sign; I kept smb2_set_security_mode(smb2,
> SMB2_NEGOTIATE_SIGNING_ENABLED); unchanged.
>
> *Wrong signature*
> When smb2_set_sign is set I get Wrong signature in received PDU,
> regardless of how many threads the program uses. This may be the same
> problem as described in #185
> <https://github.com/sahlberg/libsmb2/issues/185> and #176
> <https://github.com/sahlberg/libsmb2/issues/176>. I've modified
> smb2-signing.c so that it prints the calculated signatures and created a
> pcap of the SMB2 traffic to see what signatures the server sends us. All
> signatures are calculated correctly until we get to the Create Response
> File packet, which contains 3 SMB2 pdu's: the signature for the first SMB
> pdu matches and the those for the other two fail.
>
> The last two pdu's have the Chained flag set and the first one does not.
> I checked whether the standard
> <https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-SMB2/%5BMS-SMB2%5D.pdf>
> has anything to say about how signatures need to be calculated in case of
> chained pdu's and found a note on it in section "3.1.5.1 Verifying an
> Incoming Message". I then checked if libsmb2's signature code does anything
> special in case of pdu's that have the Chained flag set, but I didn't
> find anything. @sahlberg <https://github.com/sahlberg> Could this be the
> source of the issue?
>
> *Failed to decrypt*
> When smb2_set_seal is set and multiple threads are used as shown in the
> mwe it sometimes fails (and sometimes a single thread, sometimes both) with Failed
> to decrypt PDU. Sounds like a race condition so I started looking for
> global variables in aes related code and found some in aes.c under the
> section Private variables. That is likely the cause of the problem. I
> think the cleanest fix would be to make these members of the smb2 object,
> but the aes code is smb2_context unaware. Perhaps making them thread
> local would be a good solution, I don't know.
>

Thanks for looking at this.  I have been really really busy but it does
sound exactly like what you found.
State held in global variables in the crypto code making it not thread safe.

I would like to keep libsmb2 to use as few external features as possible,
so that it still works on very limited devices,
so I would prefer not to use thread local storage.
So I think your suggestion to move these variables into the smb2 context is
the right solution.

Can you send me a pull request by moving these into the smb2_context
structure ?

**Comment by delins** [comment]
I'll give it a go.

Meanwhile, I looked further into the other problem, regarding the invalid signatures (they are distinct bugs) and identified where it goes wrong. See this patch for the changes I made to "fix" the bug:

```.patch
diff --git a/lib/socket.c b/lib/socket.c
index 43ae81b..2a464a2 100644
--- a/lib/socket.c
+++ b/lib/socket.c
@@ -287,6 +287,7 @@ static int smb2_read_data(struct smb2_context *smb2, read_func func,
         struct iovec *tmpiov;
         int i, niov, is_chained;
         size_t num_done;
+        size_t iov_offset = 0;
         static char smb3tfrm[4] = {0xFD, 'S', 'M', 'B'};
         struct smb2_pdu *pdu = smb2->pdu;
         ssize_t count, len;
@@ -565,9 +566,9 @@ read_more_data:
             (smb2->hdr.command != SMB2_SESSION_SETUP) ) {
                 uint8_t signature[16];
                 memcpy(&signature[0], &smb2->in.iov[1].buf[48], 16);
-                if (smb2_calc_signature(smb2, &smb2->in.iov[1].buf[48],
-                                        &smb2->in.iov[1],
-                                        smb2->in.niov - 1) < 0) {
+                if (smb2_calc_signature(smb2, &smb2->in.iov[1 + iov_offset].buf[48],
+                                        &smb2->in.iov[1 + iov_offset],
+                                        smb2->in.niov - 1 - iov_offset) < 0) {
                         return -1;
                 }
                 if (memcmp(&signature[0], &smb2->in.iov[1].buf[48], 16)) {
@@ -584,6 +585,7 @@ read_more_data:
         smb2->pdu = NULL;
 
         if (is_chained) {
+                iov_offset = smb2->in.niov - 1; // Record where we ended in this loop so we know where to start in the next
                 smb2->recv_state = SMB2_RECV_HEADER;
                 smb2_add_iovector(smb2, &smb2->in, &smb2->header[0],
                                   SMB2_HEADER_SIZE, NULL);
```

This is meant as a quick hack to illustrate the issue; there may be a cleaner way but I haven't looked into the code enough to find it. 

As it turned out the issue was related to the chained messages, and all code to handle those is already in place. Also, `smb2->in.iov` and `smb2->in.niov` seem to get correctly updated in each loop of the `read_more_data` label (I verified the iov lengths with wireshark). However, the call to `smb2_calc_signature` passes `&smb2->in.iov[1]` and `smb2->in.niov - 1` each time, which means it passes all `iov`s that were read so far, while only the ones that were read in the current loop should be passed.

If you think this is the cleanest way to fix it I'll submit a pr, otherwise I'll leave it to you to find a better solution :)

**Comment by amandeepgautam** [comment]
@delins @sahlberg @s-devyatkin There is an alternate way to fix this as well. All the static variables can be declared as a local variable in  AES128_ECB_encrypt function and then passed around as function arguments. Ex.:

```
void AES128_ECB_encrypt(uint8_t* input, const uint8_t* key, uint8_t* output)
{
  // Copy input to output, and work in-memory on output
  BlockCopy(output, input);
  state_t* state = (state_t*)output;

  // The array that stores the round keys.
  uint8_t RoundKey[176];

  // The KeyExpansion routine must be called before encryption.
  KeyExpansion(key, RoundKey);

  // The next function call encrypts the PlainText with the Key using AES algorithm.
  Cipher(RoundKey, state);
}
```

**Comment by sahlberg** [comment]
> I'll give it a go.
> 
> Meanwhile, I looked further into the other problem, regarding the invalid signatures (they are distinct bugs) and identified where it goes wrong. See this patch for the changes I made to "fix" the bug:
> 
> ```diff
> diff --git a/lib/socket.c b/lib/socket.c
> index 43ae81b..2a464a2 100644
> --- a/lib/socket.c
> +++ b/lib/socket.c
> @@ -287,6 +287,7 @@ static int smb2_read_data(struct smb2_context *smb2, read_func func,
>          struct iovec *tmpiov;
>          int i, niov, is_chained;
>          size_t num_done;
> +        size_t iov_offset = 0;
>          static char smb3tfrm[4] = {0xFD, 'S', 'M', 'B'};
>          struct smb2_pdu *pdu = smb2->pdu;
>          ssize_t count, len;
> @@ -565,9 +566,9 @@ read_more_data:
>              (smb2->hdr.command != SMB2_SESSION_SETUP) ) {
>                  uint8_t signature[16];
>                  memcpy(&signature[0], &smb2->in.iov[1].buf[48], 16);
> -                if (smb2_calc_signature(smb2, &smb2->in.iov[1].buf[48],
> -                                        &smb2->in.iov[1],
> -                                        smb2->in.niov - 1) < 0) {
> +                if (smb2_calc_signature(smb2, &smb2->in.iov[1 + iov_offset].buf[48],
> +                                        &smb2->in.iov[1 + iov_offset],
> +                                        smb2->in.niov - 1 - iov_offset) < 0) {
>                          return -1;
>                  }
>                  if (memcmp(&signature[0], &smb2->in.iov[1].buf[48], 16)) {
> @@ -584,6 +585,7 @@ read_more_data:
>          smb2->pdu = NULL;
>  
>          if (is_chained) {
> +                iov_offset = smb2->in.niov - 1; // Record where we ended in this loop so we know where to start in the next
>                  smb2->recv_state = SMB2_RECV_HEADER;
>                  smb2_add_iovector(smb2, &smb2->in, &smb2->header[0],
>                                    SMB2_HEADER_SIZE, NULL);
> ```
> 
> This is meant as a quick hack to illustrate the issue; there may be a cleaner way but I haven't looked into the code enough to find it.
> 
> As it turned out the issue was related to the chained messages, and all code to handle those is already in place. Also, `smb2->in.iov` and `smb2->in.niov` seem to get correctly updated in each loop of the `read_more_data` label (I verified the iov lengths with wireshark). However, the call to `smb2_calc_signature` passes `&smb2->in.iov[1]` and `smb2->in.niov - 1` each time, which means it passes all `iov`s that were read so far, while only the ones that were read in the current loop should be passed.
> 
> If you think this is the cleanest way to fix it I'll submit a pr, otherwise I'll leave it to you to find a better solution :)

Nice. I think this looks like the right fix.
Please send a pull request.

**Comment by delins** [comment]
Pr #193 makes the globals local in aes, but it's not the only place that needs work.

The library uses [`srand`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/srand?view=msvc-160)/[`rand`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/rand?view=msvc-160) on Windows, `srandom`/`esp_random` on esp and [`srandom`](https://man7.org/linux/man-pages/man3/srandom.3.html)/[`random`](https://man7.org/linux/man-pages/man3/random.3.html) on anything else. I don't know about esp, but the other two variants are not (always) thread safe. 

Windows
`srand` and `rand` use global state and I believe concurrent access to that state is not thread safe (unless you configure the CRT to be? Not sure). They are also [not cryptographically secure](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/rand?view=msvc-160). It would for both thread safety and crypto safety be better to move to [`rand_s`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/rand-s?view=msvc-160). `rand_s` exists since XP so it should be supported on all relevant platforms.

Linux 
Linux has the [`random_r`](https://man7.org/linux/man-pages/man3/random_r.3.html) family which uses a user supplied state object. Unfortunately it's Linux specific and isn't available on FreeBSD or OSX. See [this thread](https://github.com/haskell-numerics/hmatrix/issues/279) for a relevant discussion and implementation.
Note that the `static int ctr` variable in `init.c` is also not thread safe, even though it may not matter that much. Perhaps we could move the seeding call below the `calloc` and use `smb2`'s address instead of `ctr`? Would also be less predictable I presume.

FreeBSD & OSX
I haven't looked into them yet.

**Comment by delins** [comment]
@amandeepgautam Good suggestion, I've implemented it using locals as much as possible. Only the CBC code still needs some external (not global) state, for the `iv`

**Comment by delins** [comment]
@s-devyatkin Could you confirm that the latest commit fixes the signing issue? Without sealing it should be ok now, with sealing it should be better but there are still some issues with the random number generation.

**Comment by s-devyatkin** [comment]
@delins Yes, it fixed the problem.Good job!
