### ISSUE TITLE
Use libsmb in combination with Kerberos delegation

### ISSUE THREAD

**Issue by delins** [sahlberg/libsmb2#196]
I'm building an service that runs on a server and processes data on Windows shares on some user's behalf. Users first authenticate to Kerberos, either directly or through a proxy, and then send me a TGT. Through (constrained) delegation I access the files they'd like me to process.

I'm new to Kerberos and SMB but as far as reading up on this stuff has brought me, I think this should be possible and is the correct way to do it. While most of this happens outside of libsmb, it would mean that libsmb needs to have an additional (internal) interface that takes a prenegotiated service ticket to set up the SMB connection instead of doing the whole Kerberos dance itself.

Is this on the roadmap for libsmb? How much work would it be to implement this additional interface?

**Comment by sahlberg** [comment]
That is not on the roadmap for libsmb2  and I am not sure it is even feasible to do this inside libsmb2 since it would require basically implementing both gssapi and kerberos in libsmb2.

So basically you have an existing TGT for a user that you want to use. This is more of a MIT-Kerberos question than libsmb2. 
I am not sure how to do that but you could go ask on the Kerberos lists.

**Comment by delins** [comment]
Thanks for the answer. I didn't mean to give libsmb2 the TGT and have it handle everything from there. What I was thinking of doing was to receive the TGT from a user, perform all the necessary steps to get a service ticket in my own code, and only once I have negotiated the final service ticket, I create an `smb2_context` and pass it the service ticket where you would otherwise pass a user's credentials. I think that the remaining code that needs to go into libsmb2 should then be similar in size to the code that sets up a session using user credentials, but I'm not sure.

**Comment by sahlberg** [comment]
On Wed, Apr 21, 2021 at 9:33 PM delins ***@***.***> wrote:

> Thanks for the answer. I didn't mean to give libsmb2 the TGT and have it
> handle everything from there. What I was thinking of doing was to receive
> the TGT from a user, perform all the necessary steps to get a service
> ticket in my own code, and only once I have negotiated the final service
> ticket, I create an smb2_context and pass it the service ticket where you
> would otherwise pass a user's credentials. I think that the remaining code
> that needs to go into libsmb2 should then be similar in size to the code
> that sets up a session using user credentials, but I'm not sure.
>

It is a lot more complex than that I am afraid. What is exchanged between a
client and the server during session-setup is not a service ticket but
a GSS-API wrapper wrapping a Kerberos AP request.

The gss-api is semi complex and is built using ASN.1 BER/DER. So you would
first have to write a BER/DER encoding library and run-time (or use one
that is portable enough to cover all the platforms where libsmb2 is
available)  This is a semi-large amount of code to write, maybe a minimal
implementation of BER/DER runtime would be a few thousand lines of code or
so.
A minimum GSSAPI implementation built ontop of this BER/DER runtime would
at minimum be a few thousand lines.

Then there is kerberos5. At minimum you would need to implement AP-REQ
messages, these do contain the service ticket, but in otder to authenticate
to the server it also contains an Authenticator. This authenticator is
encrypted with the session-key (which in order to get to you would need to
decrypt part of the ticket and extract the key)
then you would build the authenticator with some data (see the rfc)  and
encrypt it with with the session key.
This authenticator is what the server uses to authenticate the user. It has
to be encrypted with the same session key or else the server will fail to
decrypt and validate it.
This is another few thousand lines of code.

On top of this you will need to add a few crypto algorithms that kerberos5
uses but we don;t have in libsmb2 since we don;t need it.


I mean, it can be done but it is a LOT more work than "put the service
ticket into the packet and it will work".


Krb5 background:
Authentication in kerberos works by proof-of-possession. When you get a
ticket from the kdc you actually get two things. One blob is for the client
and is encrypted with the clients secret key. It is assumed only the client
can decrypt this blob.  This blob contains the session key.
But you also get a blob that is meant for the server, this blob is
encrypted with the servers secret key so the client can not do anything
with it, just pass it along unchanged to the server.  It is assumed only
the server can decrypt this blob. It contains a copy of the same session
key as was given to the client.

But this is not enough to do authentication because just because the client
can pass the encrypted-server-blob to the server does not mean the client
is genuine. The client could have just stolen that blob.

So, to prove to the server that the client is genuine, the client uses the
session-key, from the blob that ONLY the client could decrypt. Then it
willencrypt some data like a timestamp and some names using this session
key. So the client AP-Request will then contain BOTH the
encrypted-server-blob as well as this blob that the client created and
encrypted with the session key.
On the server side, the server decrypts the server-blob and extracts the
session key. Then it checks "can I decrypt the authenticator using this
key?"
If it can not then authentication fails.
If it CAN then it means that the client is genuine, because   The only
three computers that would know the session key would be:
1, the KDC  which created the tickets and we implicitely must trust.
2, the client, since the client is the only other computer that can decrypt
the client-blob in the ticket
3, the server, since the server is the only computer that can decrypt the
server-blob.

It is a proof of possesion kind of authentication. The fact that the
authenticator could be decrypted means that who sent it has access to the
session key
and thus it must have been the genuine client that sent it   and
authentication has completed successfully.


Sorry for the wall of text but kerberos is a lot more complex than just
"pass the ticket to the server" and would be a big thing to reimplement in
libsmb2.
But the issue can not be all that uncommon that people need to solve so I
am certain that there should be a way to inject this into the kerberos
credentials cache
but I don;t know how to do that. People on the mit kerberos mailinglist
might be able to tell you how to do this.

**Comment by sahlberg** [comment]
What I try to say is that you can not authenticate with just the service
ticket.  You need to have the secret key (the keytab) the the actual user
in order to create the additional things you need in order to authenticate
to the server.ice ticket.

**Comment by delins** [comment]
Thanks for the detailed response! Walls of text are fine :)

I had expected all this to be available in MIT's own implementation of Kerberos/GSS-API. It seems logical to me that it would contain all necessary encoding/encryption code and provide a clean API to end users, which I would imagine to look like what's in krb5-wrapper.h. My assumption that it did is also partially based on the fact that they provide sample client & server code [here](https://github.com/krb5/krb5/tree/master/src/appl/sample), which seems fine with the library alone.
