### ISSUE TITLE
smb2_rename_async failed

### ISSUE THREAD

**Issue by laoyur** [sahlberg/libsmb2#52]
this works:
```
smb2_rename_async(smb2, "abc.txt.tmp", "abc.txt", smb2_rename_cb, NULL); // succeed
```

but the following failed:
```
// failed with status == -5 in smb2_rename_cb
smb2_rename_async(smb2, "123/abc.txt.tmp", "123/abc.txt", smb2_rename_cb, NULL);
```
what does the error -5 mean ?

**Comment by afedchin** [comment]
use '\' in the path.
this should work
```c
smb2_rename_async(smb2, "123\\abc.txt.tmp", "123\\abc.txt", smb2_rename_cb, NULL);
```

**Comment by laoyur** [comment]
@afedchin thanks, it works !

`url = smb2_parse_url(smb2, "smb://user@192.168.1.1/share/abc/123.txt");`
url->path == "abc/123.txt"
why url->path not "abc\\123.txt" ? I don't understand it well.

**Comment by afedchin** [comment]
> why url->path not "abc\123.txt" ? I don't understand it well.

because it's a path in an URL. SMB should use `\` for paths. SMB path != URL path.

**Comment by laoyur** [comment]
ok, but why this works:
```
smb2_unlink(smb2, "123/abc.txt");
```
I just feel confused ...

**Comment by laoyur** [comment]
it seems like other apis accept `/`, but `smb2_rename_async ` supports `\` only ?

**Comment by amosavian** [comment]
https://github.com/sahlberg/libsmb2/commit/82cce4a441762ca03564527a5ef8f79e529848cc addressed this for open function.

**Comment by sahlberg** [comment]
smb2_rename_async is buggy. Since this function tries to emulate posix   it should
remap '/' to '\' for you, but it doesn't.
Until I fix this bug you can use the workaround that @afedchin suggested.

smb2_unlink works as expected as does mot other path paced calls since almost all calls will end up becomming a SMB2 Create + SMB2 <something> + SMB2 close chain.

SMB2 Create does this remapping.

Rename is different since it uses a Set Info command to provide the new/old names.
This is why rename behaves differently to almost all other commands.

I will fix this bug in rename.
Thanks for testing and report.

**Comment by laoyur** [comment]
@sahlberg thanks  :)
is there any chance to bring the sync version of rename ?

**Comment by sahlberg** [comment]
Please try current master.

It contains a quick fix for the '/' vs '\' isssue.
It also added a sync rename function.

It compiles  but has not been tested any furhter than that.

**Comment by laoyur** [comment]
Hi, I'm on iOS and currently using the pre-compiled lib from https://github.com/amosavian/AMSMB2
I've tried to build myself via the script provided within that project, but no luck
Your fix seems ok. I'll let you know later if I have time to make the build success.

**Comment by amosavian** [comment]
@laoyur please open an issue in AMSMB2 repository if you have any problem including failure to build.
