### ISSUE TITLE
Is libsmb2 thread safe?

### ISSUE THREAD

**Issue by amosavian** [sahlberg/libsmb2#53]
Hi,

Is it safe to use `smb2_context` in multiple concurrent threads in order to execute file operation functions? What about `smb2fh` and `smb2dir`?

In other words, is it safe to call 2 different functions on same context from two different threads?

**Comment by sahlberg** [comment]
It is no threads safe. So only call it from a single thread or protect the
calls through a futex.

**Comment by amosavian** [comment]
Considering async functions, I need to pthread_mutex lock before calling that async function and unlock mutex just after function returns? Or I should wait for callback execution to unlock mutex?

**Comment by sahlberg** [comment]
On Tue, Jun 12, 2018 at 2:44 PM, Amir Abbas Mousavian <
notifications@github.com> wrote:

> Considering async functions, I need to pthread_mutex lock before calling
> that async function and unlock mutex just after function returns?
>
Yepp.  And the async function should return almost immediately so you only
hold the lock for a very short time.
You also need to take the mutex before you call smb2_service() and release
it afterwards.

All the callbacks will be invoked from smb2_service() so anything that
happens in a callback is already done within a mutex.
This does mean that if you invoke/call other *_async() functions from
within the callback itself, then you do not need to wrap that call in
a mutex since it is already protected by a mutex.

**Comment by amosavian** [comment]
Thanks, thats great. What about `smb2_which_events()`?
