### ISSUE TITLE
Add backup intent support

### ISSUE THREAD

**Issue by haihongwang** [sahlberg/libsmb2#66]
Currently there is no support to add backup intent flag in SMB2 CREATE request.

Wonder what is the right way to do this? Add an extra API to set some flag in smb2_context?

**Comment by sahlberg** [comment]
There are a couple of ways of doing this.

The easiest way would be to add a new flag, something like O_BACKUPINTENT,
to the flags that smb2_open() takes.
That is the easiest way. Not sure if that is the right way to go since does
that mean that we should add ntfs specific flags left
right and centre to smb2_open()?
Would also have to be careful so whatever that flag is picked as, that it
does not collide with any of the flags we do support on any
of the platforms we support.
That said,
#define O_BACKUPINTENT 0x80000000
should be fairly safe.



A better way, but more work, is probably that if you need O_BACKUPINTENT,
then you
call smb2_cmd_create_async() directly since then you can pass in whatever
flags or other fields you want to the SMB2 command.
I.e. create your own wrapper around smb2_cmd_create_async() and use it to
open the file.
This is not too much work either since you can basically just copy most of
the code you need from smb2_open_async().

The problem then is that you probably want to create a struct smb2fh  sicne
that is what you will need in order to call
smb2_read()/write/ etc.
And struct smb2fh is private to libsmb2.c.

To solve that you would need to create two new public functions for
libsmb2.c.
1,  smb2_allocate_smb2fh(smb2)   which just allocates and initializes this
structure.  You call this from your code and pass this pointer as
the private pointer to smb2_cmd_create_async().

2, smb2_smb2fh_set_fileid(smb2, smb2fh, file_id)
which you call from your callback to the create_async() and use to
initialize the file_id of the structure.
Just like the private open_cb() function in libsmb2.c does.

These two functions should be easy to set up.
Once you have them you can then have access to the full semantics of what
smb2_cmd_create_async() can offer and still convert the response back into
a smb2fh so that from there on you can use the much niver high level api
such as smb2_[p]read/[p]write etc.




I think the second option is preferable since that way you can get access
to the full semantics of SMB2 CREATE. and not just this particular flag.
You get access to all other smb2/ntfs specific flags, you can access
impersonation levev, create disposition, etc ...
I think that is a much more powerful solution for you.
But it will need you create these two new functions and expose them from
libsmb2.c

regards
ronnie sahlberg

**Comment by amosavian** [comment]
Indeed I’m creating raw buffer with size of smb2fh and calculate the location of file id field. This would eliminate necessarity my hack.

**Comment by sahlberg** [comment]
I pushed a change to master that adds a function you can use to create a
smb2fh based on the file_id

Please try it out and let me know if this is sufficient to avoid having to
the hack.

**Comment by sahlberg** [comment]
I think there is nothing more to do here.
Users that want backup intent can use the low level smb3 functions to open the file.
