### ISSUE TITLE
why not support number of links

### ISSUE THREAD

**Issue by kasimok** [sahlberg/libsmb2#78]
in "libsmb2.c" I can see we set the  "ent->dirent.st.smb2_nlink = 0;", is this a limitation?  I though this might help to get child file count of a directory, but now I can only get a "0"

**Comment by sahlberg** [comment]
To really get a correct link count we would need the Posix Extension to be
fully implemented.

This only exist right now for SMB1 but not SMB2.
We are working on getting it into SMB2 for both the clients as well as
samba.
It will take a little while before this will be available, but it will be
there eventually.

Probably/hopefully before the end of this year.

**Comment by kasimok** [comment]
Understood. Could you please give me a little more hint about it? I can pull a branch and start researching. Thanks!

**Comment by sahlberg** [comment]
If you want t help speed this up you should reach out to the samba project
and help them work on finishing, testing and documenting how thee
extensions will work on SMB2 (they will work differently, and in an
incompatible way to SMB1 :-()
There is also a need for tooling to do conversion of filesystem semantics
from SMB1 compatible features to SMB2 compatible features.
So that people can migrate a server from SMB1 + posix extensions to become
SMB2 + posix extensions.

This is all work and specifications that are being developed right now in
samba, but all help will be appreciated. Manpower is always a shortage in
open source.

IMHO There is probably at least a year before we can start using this in
production or in libsmb2.
