### ISSUE TITLE
no error string set as part of compound pdus

### ISSUE THREAD

**Issue by amandeepgautam** [sahlberg/libsmb2#98]
when we use compound pdus, for example, smb2_cmd_open_async, smb2_cmd_read_async and smb2_cmd_close_async we do not get any error string from smb2_get_error() as probably it is not set. Is there any particular reason for this behaviour?

 On top of that, smb2_set_error is private so we do not have the ability to set the error from our code.
In our use case is that we are using compound pdus and high-level API's provided by the library like smb2_pread_async interchangeably. So availability of the error string becomes inconsistent in the two different code path. 

Any suggestions?

**Comment by sahlberg** [comment]
On Wed, Aug 14, 2019 at 9:38 AM Aman Deep Gautam <notifications@github.com>
wrote:

> when we use compound pdus, for example, smb2_cmd_open_async,
> smb2_cmd_read_async and smb2_cmd_close_async we do not get any error string
> from smb2_get_error() as probably it is not set. Is there any particular
> reason for this behaviour?
>
smb2_get_error() should always return the error string for the most recent
error that has happened.
If the compound failed, or one of the component in the compound failed, and
there is no error string in smb2_get_error() then that is a bug.

Most likely it is due to an error handler somewhere that forgets to set
smb2_set_error().

Do you have a specific instance of a compound that contains an error and
where smb2_get_error() is empty afterwards ?

**Comment by sahlberg** [comment]
declaring github issues bancruptcy
